driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
     recipe[test::default]
