name 'chef_user'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_user'
long_description 'Installs/Configures chef_user'
version '0.1.0'
depends 'java'
