default[:AMD_DB_SERVER][:db_ami_ID] = 'ami-c7d092f7'
default[:AMD_DB_SERVER][:instance_type] = 't2.small'
default[:AMD_DB_SERVER][:key_name] = 'amdkeypair'
default[:AMD_DB_SERVER][:key_path] = '~/.chef/keys/amdkeypair.pem'
default[:AMD_DB_SERVER][:pvt_subnet_ID] = 'amd_pvt_subnet'
default[:AMD_DB_SERVER][:sg_ID] = 'amd_sg'
default[:AMD_DB_SERVER][:tag] = 'medengine_db'
default[:AMD_DB_SERVER][:db_machine_name] = 'medenginedbserverdemo2'
default[:AMD_DB_SERVER][:app_machine_name] = 'medengineappserver'

default[:AMD_DB_SERVER][:ami_ID] = 'ami-c7d092f7'
default[:AMD_DB_SERVER][:nginx_ami_ID] = 'ami-9abea4fb'
default[:AMD_DB_SERVER][:nginx_machine_name] = 'amdnginxserver'
default[:AMD_DB_SERVER][:pub_subnet_ID] = 'amd_pub_subnet'

